typography_spectrum: 0.5843924200162292
color:
  brandStrength: 0.625702161109075
  lightness: 0.5661105813924223
  saturation: 0.9745177233126014
  rhythmicContrast: 0.4369599614292383
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/5073037a-d3d5-4597-8840-163f08b8eca9.gif
  appId: 'https://www.facebook.com/eli.brouwer.3'
layout_spectrum: 0.8520614611916244
author:
  name: Eli
name: drifttree
navigation:
  - name: intro
    id: d34a3a24-cacd-4af1-9fca-f9a389389693
    type: content
title: Open thoughts
content: []
description: ''
