typography_spectrum: 0.3892044925284895
color:
  brandStrength: 0.6275531462507119
  lightness: 0.5698847552838893
  saturation: 0.9718302988154942
  rhythmicContrast: 0.4393447644065254
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/5073037a-d3d5-4597-8840-163f08b8eca9.gif
  appId: 'https://www.facebook.com/eli.brouwer.3'
layout_spectrum: 0.09865969366606067
author:
  name: Eli
name: drifttree
navigation:
  - name: intro
    id: d34a3a24-cacd-4af1-9fca-f9a389389693
    type: content
  - name: My music
    id: 2af9d5a3-3738-4bd4-880a-51531f4fffdd
    type: content
title: Open thoughts
content: []
description: ''
purpose:
  - type: contact
    url: 'mailto:eli.brouwer@gmail.com'
    label: Contact
