typography_spectrum: 0.3892044925284895
color:
  brandStrength: 0.6275531462507119
  lightness: 0.5698847552838893
  saturation: 0.9718302988154942
  rhythmicContrast: 0.4393447644065254
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/5073037a-d3d5-4597-8840-163f08b8eca9.gif
  appId: 'https://www.facebook.com/eli.brouwer.3'
layout_spectrum: 0.09865969366606067
author:
  name: Eli
name: drifttree
navigation:
  - name: intro
    id: d34a3a24-cacd-4af1-9fca-f9a389389693
    type: content
  - name: My music
    id: 2af9d5a3-3738-4bd4-880a-51531f4fffdd
    type: content
title: Open thoughts
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/18d0cb67-fb65-4aa0-9e3e-920d9ce61d27.gif">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/18d0cb67-fb65-4aa0-9e3e-920d9ce61d27.gif
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: The shit to share
purpose: []
